---
title: "Joining the Lab"
toc: true
---

The success of the Belief System Lab depends on the work of kind, passionate, and intelligent people. Thank you for considering joining the lab. A living draft of our lab philosophy is [here](philosophy.qmd).

## Bachelor Student Research Opportunities

*This is currently under construction*

## PhD Research Opportunities

*I will not be recruiting PhD students at Michigan State University.*

There is not an ideal person for the lab. Instead, I am looking for people who are motivated to study belief systems and political psychology (broadly speaking). I explicitly aim to build a lab with people from diverse backgrounds and with unique experiences and perspectives.

## Postdoctoral Researchers & Visiting Scholars

 - If you are interested in working as a postdoc in the lab, please contact Mark to make arrangements. Unless otherwise specified, postdocs will need to obtain external funding to support their stay. For example, the [Marie Skłodowska-Curie Global Fellowship](https://ec.europa.eu/research/mariecurieactions/actions/individual-fellowships_en).

 - If you are a PhD student, postdoc, or faculty at another institution and are interested in visiting the lab as a visiting scholar (i.e. hangout and work on some projects), please contact Mark.
