---
title: "Lab Philosophy"
toc: false
---


Our research goal is to understand ideological and moral beliefs – such as political ideology, racism, religious fundamentalism, and moral conviction – and how they structure attitudes and behaviors, how they provide people with meaning, and why people adopt them in the first place. We will treat our participants with respect and dignity while doing work that is methodologically rigorous and advances knowledge on belief systems.

The lab environment aims to be inclusive, cooperative, healthy, respectful, and kind. We expect lab members to work hard, take responsibility for their tasks, complete their goals. We help each other meet these expectations by collaborating on problems and projects, communicating our challenges, providing timely and actionable feedback, and continuously working together to improve our work environment.

Part of a good work environment is the prioritization of the health and well-being of the lab members. This means that lab members are encouraged to take time-off, to rest when they are sick, and to develop a rich life outside of the lab. Often times the precise timing of research goals can be rearranged to accommodate course schedules, unexpected life events etc. By communicating and collaborating, we can meet our research goals and maintain our health and well-being.

This lab philosophy will be updated in the future based on the experiences, wishes, and goals of lab members.
